#服务的端口
server:
  port: 8791

#项目模块的名称
spring:
  application:
    name: service-feign-1

#指向注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#开启断路器
feign:
  hystrix:
    enabled: true