server:
  port: 8801

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: service-ribbon-1
    api-b:
      path: /api-feign/**
      serviceId: service-feign-1